// GENERATED by nice-generate-exports — do not edit by hand
// To update: edit package.exports.json and run `npm run generate-exports`

/** Syntax-highlighted code block component for nice-react using Shiki and design tokens. */

export { default } from "./components/Code"
export * from "./components/Code"
export { getCodeToken } from "./tokens"
